# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.delete_nth as module_0
import collections as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    set_0 = set()
    var_0 = module_0.delete_nth_naive(set_0, set_0)
    var_1 = module_0.delete_nth_naive(set_0, set_0)
    var_2 = module_0.delete_nth(set_0, set_0)
    var_3 = module_0.delete_nth(set_0, var_1)
    var_4 = var_3.__eq__(set_0)
    var_5 = module_0.delete_nth(var_2, set_0)
    bytes_0 = b"\xb8\xad\xe63C\xe4\x1a\xf8X\xf4"
    module_0.delete_nth_naive(bytes_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    tuple_0 = ()
    var_0 = module_0.delete_nth(tuple_0, tuple_0)
    var_1 = module_0.delete_nth_naive(var_0, tuple_0)
    var_2 = module_0.delete_nth(var_1, var_1)
    var_3 = module_0.delete_nth(var_0, var_0)
    tuple_0.__setitem__(tuple_0, tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x7f\xb9\xca\n4\xed\xf9\xfd\xc3\xac"
    module_0.delete_nth(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -216
    module_0.delete_nth_naive(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    tuple_0 = ()
    ordered_dict_keys_view_0 = module_1._OrderedDictKeysView(tuple_0)
    var_0 = ordered_dict_keys_view_0.__contains__(ordered_dict_keys_view_0)
    var_1 = module_0.delete_nth_naive(
        ordered_dict_keys_view_0, ordered_dict_keys_view_0
    )
    list_0 = [tuple_0]
    none_type_0 = None
    var_2 = module_0.delete_nth(tuple_0, none_type_0)
    var_3 = module_0.delete_nth(list_0, var_0)
    var_1.__iadd__(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    tuple_0 = ()
    var_0 = module_0.delete_nth_naive(tuple_0, tuple_0)
    var_1 = module_0.delete_nth(tuple_0, tuple_0)
    list_0 = [tuple_0]
    var_2 = var_1.__ge__(var_1)
    var_3 = module_0.delete_nth(list_0, var_2)
    var_2.__iadd__(var_3)


@pytest.mark.xfail(strict=True)
def test_case_6():
    tuple_0 = ()
    ordered_dict_keys_view_0 = module_1._OrderedDictKeysView(tuple_0)
    var_0 = ordered_dict_keys_view_0.__contains__(ordered_dict_keys_view_0)
    list_0 = [tuple_0]
    var_1 = module_0.delete_nth_naive(list_0, var_0)
    var_0.isdigit()


@pytest.mark.xfail(strict=True)
def test_case_7():
    tuple_0 = ()
    var_0 = module_0.delete_nth(tuple_0, tuple_0)
    var_1 = module_0.delete_nth_naive(var_0, var_0)
    var_2 = module_0.delete_nth(tuple_0, tuple_0)
    list_0 = [var_0]
    var_3 = list_0.__contains__(var_2)
    var_4 = module_0.delete_nth_naive(list_0, var_3)
    var_4.join(var_2)
